spring.datasource.url=jdbc:mysql://127.0.0.1:3307/jobportal_db
spring.datasource.username=root
spring.datasource.password=Nazmashaik@22

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
